language: go
sudo: false

go:
  - 1.16
  - 1.17
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN
